ALTER TABLE `userGroup` ADD FOREIGN KEY (`group`) REFERENCES `group` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `userGroup` ADD FOREIGN KEY (`user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `profile` ADD FOREIGN KEY (`gender`) REFERENCES `gender` (`code`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `profile` ADD FOREIGN KEY (`user`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

